{"name": "test_add[except]", "status": "failed", "statusDetails": {"message": "AssertionError: assert None == '请输入数字！'\n  +None\n  -'请输入数字！'", "trace": "self = <calculator.test_cal_new.TestCalc object at 0x00000235A6C10FD0>\nget_calc = <calculator.calculator.Calculator object at 0x00000235A6BEC5E0>\nget_add_datas = ['', 5, '请输入数字！']\n\n    @allure.story(\"测试加法\")\n    @pytest.mark.run(order=1)\n    def test_add(self, get_calc, get_add_datas):\n        result = None\n        try:\n            result = get_calc.add(get_add_datas[0], get_add_datas[1])\n            if isinstance(result, float):\n                result = round(result, 2)\n        except Exception as e:\n            print(e)\n>       assert result == get_add_datas[2]\nE       AssertionError: assert None == '请输入数字！'\nE         +None\nE         -'请输入数字！'\n\ntest_cal_new.py:19: AssertionError"}, "parameters": [{"name": "get_add_datas", "value": "['', 5, '请输入数字！']"}], "start": 1610117962231, "stop": 1610117962231, "uuid": "deb9c011-0a85-4e4e-85d9-7e561edd20fd", "historyId": "1e2d00ba5be095891cc114079d74eff1", "testCaseId": "eb800816794e42af7255c44db9e2a513", "fullName": "calculator.test_cal_new.TestCalc#test_add", "labels": [{"name": "feature", "value": "测试计算器"}, {"name": "story", "value": "测试加法"}, {"name": "tag", "value": "run(order=1)"}, {"name": "parentSuite", "value": "calculator"}, {"name": "suite", "value": "test_cal_new"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "A-202012121859I"}, {"name": "thread", "value": "280-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "calculator.test_cal_new"}]}